import { useEffect, useState } from "react"

import Layout from "../components/Layout"

import { db, auth } from "../firebase"

import {
  collection,
  addDoc,
  query,
  where,
  onSnapshot,
} from "firebase/firestore"

import jsPDF from "jspdf"

function Orders() {

  const [orders, setOrders] = useState([])

  const [showModal, setShowModal] = useState(false)

  const [platform, setPlatform] = useState("")
  const [documentType, setDocumentType] = useState("")

  const [searchTerm, setSearchTerm] = useState("")
  const [statusFilter, setStatusFilter] = useState("All")

  useEffect(() => {

    const q = query(
      collection(db, "orders"),
      where("userId", "==", auth.currentUser.uid)
    )

    const unsubscribe = onSnapshot(
      q,
      (snapshot) => {

        const ordersData = snapshot.docs.map((doc) => ({
          id: doc.id,
          ...doc.data(),
        }))

        setOrders(ordersData)

      }
    )

    return () => unsubscribe()

  }, [])

  const handleCreateOrder = async () => {

    if (!platform || !documentType) return

    const newOrder = {

      userId: auth.currentUser.uid,

      orderId:
        "#" +
        Math.floor(Math.random() * 999999),

      platform,

      document: documentType,

      status: "Pending",

      printer:
        documentType === "Shipping Label"
          ? "Thermal Printer"
          : "A4 Printer",

      createdAt: Date.now(),

    }

    await addDoc(
      collection(db, "orders"),
      newOrder
    )

    await addDoc(collection(db, "logs"), {

      userId: auth.currentUser.uid,

      action: `${platform} order created`,

      time: "Just now",

      status: "Pending",

      createdAt: Date.now(),

    })

    setPlatform("")
    setDocumentType("")

    setShowModal(false)

  }

  const handleStatusChange = (id, newStatus) => {

    const updatedOrders = orders.map((order) => {

      if (order.id === id) {

        return {
          ...order,
          status: newStatus,
        }

      }

      return order

    })

    setOrders(updatedOrders)

  }

  const generatePDF = (order) => {

    const doc = new jsPDF()

    // PAGE BACKGROUND

    doc.setFillColor(240, 242, 245)

    doc.rect(
      0,
      0,
      210,
      297,
      "F"
    )

    // MAIN CARD

    doc.setFillColor(255, 255, 255)

    doc.roundedRect(
      30,
      25,
      150,
      230,
      10,
      10,
      "F"
    )

    // OUTER CIRCLE

    doc.setFillColor(230, 232, 255)

    doc.circle(
      105,
      55,
      16,
      "F"
    )

    // INNER CIRCLE

    doc.setFillColor(99, 102, 241)

    doc.circle(
      105,
      55,
      10,
      "F"
    )

    // CHECK ICON

    doc.setTextColor(255, 255, 255)

    doc.setFontSize(18)

    doc.text(
      "✓",
      102,
      59
    )

    // TITLE

    doc.setTextColor(20, 20, 20)

    doc.setFontSize(24)

    doc.text(
      "Success! Your Order",
      55,
      90
    )

    doc.text(
      "is Ready",
      82,
      104
    )

    // SUBTITLE

    doc.setTextColor(120, 120, 120)

    doc.setFontSize(11)

    doc.text(
      "Your document has been generated successfully.",
      46,
      120
    )

    // INFO BOX

    doc.setFillColor(248, 248, 248)

    doc.roundedRect(
      42,
      140,
      126,
      65,
      8,
      8,
      "F"
    )

    // LABELS

    doc.setTextColor(140, 140, 140)

    doc.setFontSize(11)

    doc.text(
      "Order Number",
      50,
      158
    )

    doc.text(
      "Platform",
      50,
      172
    )

    doc.text(
      "Document",
      50,
      186
    )

    doc.text(
      "Printer",
      50,
      200
    )

    // VALUES

    doc.setTextColor(20, 20, 20)

    doc.text(
      order.orderId,
      120,
      158
    )

    doc.text(
      order.platform,
      120,
      172
    )

    doc.text(
      order.document,
      120,
      186
    )

    doc.text(
      order.printer,
      120,
      200
    )

    // BUTTON

    doc.setFillColor(10, 10, 70)

    doc.roundedRect(
      52,
      225,
      105,
      20,
      12,
      12,
      "F"
    )

    doc.setTextColor(255, 255, 255)

    doc.setFontSize(14)

    doc.text(
      "Generated by OrderPrint",
      73,
      238
    )

    // SAVE

    doc.save(
      `${order.orderId}.pdf`
    )

  }

  const filteredOrders = orders.filter((order) => {

    const matchesSearch =
      order.orderId
        .toLowerCase()
        .includes(searchTerm.toLowerCase())

    const matchesStatus =
      statusFilter === "All"
        ? true
        : order.status === statusFilter

    return matchesSearch && matchesStatus

  })

  return (

    <Layout>

      <div className="flex flex-col lg:flex-row lg:items-start justify-between gap-5 mb-10">

        <div>

          <h1 className="text-4xl lg:text-5xl font-bold mb-3 dark:text-white">
            Orders
          </h1>

          <p className="text-gray-500 dark:text-gray-400">
            Manage print orders
          </p>

        </div>

        <button
          onClick={() =>
            setShowModal(true)
          }
          className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-4 rounded-2xl"
        >
          + Create Order
        </button>

      </div>

      {/* SEARCH */}

      <div className="flex flex-col lg:flex-row gap-4 mb-8">

        <input
          type="text"
          placeholder="Search Order ID..."
          value={searchTerm}
          onChange={(e) =>
            setSearchTerm(
              e.target.value
            )
          }
          className="flex-1 p-4 rounded-2xl border border-gray-300 dark:border-slate-600 dark:bg-slate-800 dark:text-white outline-none"
        />

        <select
          value={statusFilter}
          onChange={(e) =>
            setStatusFilter(
              e.target.value
            )
          }
          className="p-4 rounded-2xl border border-gray-300 dark:border-slate-600 dark:bg-slate-800 dark:text-white outline-none"
        >

          <option>
            All
          </option>

          <option>
            Pending
          </option>

          <option>
            Processing
          </option>

          <option>
            Printed
          </option>

          <option>
            Failed
          </option>

        </select>

      </div>

      {/* ORDERS */}

      <div className="space-y-5">

        {

          filteredOrders.map((order) => (

            <div
              key={order.id}
              className="bg-white dark:bg-slate-800 border border-gray-200 dark:border-slate-700 rounded-3xl p-6 shadow-sm"
            >

              <div className="flex flex-col lg:flex-row lg:items-start justify-between gap-6 mb-6">

                <div>

                  <h2 className="text-2xl font-bold mb-2 dark:text-white">
                    {order.orderId}
                  </h2>

                  <p className="text-gray-500 dark:text-gray-400 mb-1">

                    Platform:

                    <span className="ml-2 font-medium text-black dark:text-white">

                      {order.platform}

                    </span>

                  </p>

                  <p className="text-gray-500 dark:text-gray-400 mb-1">

                    Document:

                    <span className="ml-2 font-medium text-black dark:text-white">

                      {order.document}

                    </span>

                  </p>

                  <p className="text-gray-500 dark:text-gray-400">

                    Printer:

                    <span className="ml-2 font-medium text-black dark:text-white">

                      {order.printer}

                    </span>

                  </p>

                </div>

                <span
                  className={`px-5 py-2 rounded-full text-sm font-medium h-fit

                  ${
                    order.status ===
                    "Printed"

                      ? "bg-green-100 text-green-600"

                      : order.status ===
                        "Pending"

                      ? "bg-yellow-100 text-yellow-600"

                      : order.status ===
                        "Processing"

                      ? "bg-blue-100 text-blue-600"

                      : "bg-red-100 text-red-600"
                  }

                `}
                >

                  {order.status}

                </span>

              </div>

              <div className="flex flex-wrap gap-3">

                <button
                  onClick={() =>
                    handleStatusChange(
                      order.id,
                      "Pending"
                    )
                  }
                  className="bg-yellow-500 hover:bg-yellow-600 text-white px-5 py-3 rounded-2xl"
                >
                  Pending
                </button>

                <button
                  onClick={() =>
                    handleStatusChange(
                      order.id,
                      "Processing"
                    )
                  }
                  className="bg-blue-500 hover:bg-blue-600 text-white px-5 py-3 rounded-2xl"
                >
                  Processing
                </button>

                <button
                  onClick={() =>
                    handleStatusChange(
                      order.id,
                      "Printed"
                    )
                  }
                  className="bg-green-500 hover:bg-green-600 text-white px-5 py-3 rounded-2xl"
                >
                  Printed
                </button>

                <button
                  onClick={() =>
                    handleStatusChange(
                      order.id,
                      "Failed"
                    )
                  }
                  className="bg-red-500 hover:bg-red-600 text-white px-5 py-3 rounded-2xl"
                >
                  Failed
                </button>

                <button
                  onClick={() =>
                    generatePDF(order)
                  }
                  className="bg-purple-600 hover:bg-purple-700 text-white px-5 py-3 rounded-2xl"
                >
                  Download PDF
                </button>

              </div>

            </div>

          ))

        }

      </div>

      {/* MODAL */}

      {

        showModal && (

          <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">

            <div className="bg-white dark:bg-slate-800 w-full max-w-[500px] rounded-3xl p-8">

              <div className="flex items-center justify-between mb-8">

                <h2 className="text-3xl font-bold dark:text-white">
                  Create Order
                </h2>

                <button
                  onClick={() =>
                    setShowModal(false)
                  }
                  className="text-gray-500 text-2xl"
                >
                  ×
                </button>

              </div>

              <select
                value={platform}
                onChange={(e) =>
                  setPlatform(
                    e.target.value
                  )
                }
                className="w-full p-4 rounded-2xl border border-gray-300 dark:border-slate-600 dark:bg-slate-700 dark:text-white mb-5 outline-none"
              >

                <option value="">
                  Select Platform
                </option>

                <option>
                  Amazon
                </option>

                <option>
                  Flipkart
                </option>

                <option>
                  Meesho
                </option>

              </select>

              <select
                value={documentType}
                onChange={(e) =>
                  setDocumentType(
                    e.target.value
                  )
                }
                className="w-full p-4 rounded-2xl border border-gray-300 dark:border-slate-600 dark:bg-slate-700 dark:text-white mb-8 outline-none"
              >

                <option value="">
                  Select Document
                </option>

                <option>
                  Shipping Label
                </option>

                <option>
                  Invoice
                </option>

                <option>
                  Packing Slip
                </option>

              </select>

              <button
                onClick={
                  handleCreateOrder
                }
                className="w-full bg-blue-600 hover:bg-blue-700 text-white p-4 rounded-2xl"
              >
                Create Order
              </button>

            </div>

          </div>

        )

      }

    </Layout>

  )
}

export default Orders